dist: 
  - trusty
sudo: required
language:
  - generic
cache:
  - apt


before_install:
  - echo "CI pre install"
  

script:
  - cd emreay-/utility/setup-this-machine
  - ./setup-this-machine.sh dep
