dist: 
  - trusty
sudo: required
language:
  - generic
cache:
  - apt


before_install:
  - echo "CI pre install"
  

script:
  - pwd
  - ls
  - find . -name "setup-this-machine.sh"
  - cd $(dirname $(find . -name "setup-this-machine.sh"))
  - ./setup-this-machine.sh dep
